changelog:
  file: "CHANGELOG.md"
  types:
    feat: "Features"
    fix: "Bug Fixes"
    docs: "Documentation"
    style: "Styles"
    refactor: "Code Refactoring"
    perf: "Performance Improvements"
    test: "Tests"
    build: "Build System"
    ci: "Continuous Integration"
    chore: "Chores"
    revert: "Reverts"
  includeHash: true
  includeDate: true
  includeAuthor: false
version:
  files: ["package.json"]
  tagPrefix: "v"
  tagMessage: "Release {version}"
  commitMessage: "chore(release): {version}"
commits:
  conventional: true
  allowCustomTypes: true
git:
  push: true
  pushTags: true
  signTags: false
  signCommits: false